# Generated by Django 3.2.6 on 2021-09-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variatios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variatios',
            new_name='variations',
        ),
    ]
